### PR TITLE
Test MacOS X build

### PR DESCRIPTION
**Pull request by juliotux**
Test build the package for OS X support

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by juliotux** [comment]
@conda-forge-admin, please rerender

**Comment by wolfv** [comment]
hey, coming from gitter: 

here seems to be your issue:

```
    SRCDIR=$SRC_DIR BUILDDIR=$SRC_DIR install.sharedlibstub 
make[1]: Entering directory '$SRC_DIR/lib'
$SRC_DIR/buildtools/mkinstalldirs /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp.LbZwIDyw/link
mkdir /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp.LbZwIDyw/link
cd /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp.LbZwIDyw/link/ ; \
          rm -f libnetpbm.dylib; \
ln -s ../lib/libnetpbm.11.73.dylib libnetpbm.dylib
make[1]: Leaving directory '$SRC_DIR/lib'

Netpbm has been successfully packaged under directory
/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp.LbZwIDyw.  Run 'installnetpbm' to install it on your system.

Resource usage statistics from building netpbm:
   Process count: 9
   CPU time: Sys=0:00:04.5, User=0:00:09.4
   Memory: 52.3M
   Disk usage: 65.2K
   Time elapsed: 0:03:05.9

Packaging netpbm
INFO:conda_build.build:Packaging netpbm
INFO conda_build.build:build(1570): Packaging netpbm
Packaging netpbm-10.73.28-pl526h79c4ae5_1
INFO:conda_build.build:Packaging netpbm-10.73.28-pl526h79c4ae5_1
INFO conda_build.build:bundle_conda(891): Packaging netpbm-10.73.28-pl526h79c4ae5_1
number of files: 388
Fixing linking of @rpath/libjpeg.9.dylib in /usr/local/miniconda/conda-bld/netpbm_1568562933198/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/jpegtopnm
New link location is None
Fixing linking of /libnetpbm.11.dylib in /usr/local/miniconda/conda-bld/netpbm_1568562933198/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/jpegtopnm
New link location is None
Fixing linking of /usr/lib/libSystem.B.dylib in /usr/local/miniconda/conda-bld/netpbm_1568562933198/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/jpegtopnm
New link location is None
```

Do you need to run `Run 'installnetpbm' to install it on your system.` (with the correct conda prefix)?
I think your build script doesn't place/produce libnetpbm.11.dylib correctly, could that be it?

**Comment by juliotux** [comment]
@wolfv, sorry for the late comment. I tryied with `./installnetpbm`, but it is a interactive command line program. I'm checking with the developer of the program if there is a silent alternative.

**Comment by juliotux** [comment]
@wolfv I checked with the developer and the `./installnetpbm` just copy the files from `pkgdir` to the `$PREFIX`, what I already do. But the linker is linking the packages to a non-existing `/libnetpbm.11.dylib`, when it should link it to `$PREFIX/lib/libnetpbm.11.dylib`. It is a very strange behavior that I couldn't find any solution.

**Comment by juliotux** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
